### ISSUE TITLE
Ring blocks don't get detected on the demo site

### ISSUE THREAD

**Issue by jupiterio** [scratchblocks/scratchblocks#207] opened 2016-12-06 18:44 UTC
They appear as obsolete and don't have the ring slot. They also fail to be rendered if there isn't new lines between `{`, `}`, and the blocks inside them.
[demo site (without newlines)](http://scratchblocks.github.io/#Hello%2C%20Scratchblocks3!%20(%7BSnap!%20%3A%3A%20control%0Arun%20(%7B%7D%20%40addInput)%20%40addInput%20%3A%3A%20control%7D%20%40addInput)%20%3A%3A%20%237a2)
[demo site (with newlines)](http://scratchblocks.github.io/#Hello%2C%20Scratchblocks3!%20(%7B%0ASnap!%20%3A%3A%20control%0Arun%20(%7B%7D%20%40addInput)%20%40addInput%20%3A%3A%20control%0A%7D%20%40addInput)%20%3A%3A%20%237a2)
[scratch (agnostic to new lines in the ring slot)](https://scratch.mit.edu/discuss/post/2327241/)

Obviously this is not too urgent. I'm guessing it's just some sync problem between the version on Github and Scratch.

**Comment by tjvr** [comment] 2016-12-06 22:04
Interesting. Presumably this is a regression; the version on the forums should in theory be older.

**Comment by tjvr** [comment] 2017-02-05 13:03
Ignore the above. I remember now:

- You need `:: grey ring` for something to look like a ring.
- `{}` gets rendered as an embedded command, unless it's inside a ring.
- `{\n}` is always rendered as an embedded script (e.g. the inside of an "if" block).
- The forums probably mangle newlines/whitespace in irritating ways. The conversion from BBCode to HTML isn't always convenient. 

If anyone wants to fix the inconsistency by sending a PR to scratch-forums, be my guest!

**Comment by tjvr** [comment] 2019-05-12 20:22
Closing due to the above -- rings should be written `({stamp} :: grey ring))`.

Note that the Scratch 3.0 renderer deliberately doesn't support rings.

**Closed by tjvr** 2019-05-12 20:22 UTC
Labels: forums, wontfix

**Comment by Jonathan50** [comment] 2019-05-17 04:21
> Closing due to the above -- rings should be written `({stamp} :: grey ring))`.

But it should be `({stamp} @addInput)`: https://github.com/scratchblocks/scratchblocks/releases/tag/v3.1 That works on the forums, and used to work on the wiki.
